// Currency
export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';

// Coins market list
export const FETCH_COINS_REQUEST = 'FETCH_COINS_REQUEST';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_FAILURE = 'FETCH_COINS_FAILURE';

// Chart
export const TOGGLE_CHART_COIN = 'TOGGLE_CHART_COIN';
export const SET_CHART_RANGE = 'SET_CHART_RANGE';
export const SET_CHART_TYPE = 'SET_CHART_TYPE';
export const FETCH_CHART_REQUEST = 'FETCH_CHART_REQUEST';
export const FETCH_CHART_SUCCESS = 'FETCH_CHART_SUCCESS';
export const FETCH_CHART_FAILURE = 'FETCH_CHART_FAILURE';

// Exchange / converter
export const SET_EXCHANGE_SELL = 'SET_EXCHANGE_SELL';
export const SET_EXCHANGE_BUY = 'SET_EXCHANGE_BUY';
export const SET_EXCHANGE_AMOUNT = 'SET_EXCHANGE_AMOUNT';
export const SET_EXCHANGE_ERROR = 'SET_EXCHANGE_ERROR';
export const FETCH_RATE_REQUEST = 'FETCH_RATE_REQUEST';
export const FETCH_RATE_SUCCESS = 'FETCH_RATE_SUCCESS';
export const FETCH_RATE_FAILURE = 'FETCH_RATE_FAILURE';

// Search
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const SET_ACTIVE_COIN = 'SET_ACTIVE_COIN';
